export const GET_ERRORS = "GET_ERRORS";
export const GET_MESSAGES = "GET_MESSAGES";

export const SET_LANGUAGE = "SET_LANGUAGE";
export const GET_USER = "GET_USER";
export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_SPORT_TYPE = "GET_SPORT_TYPE";
export const OPEN_NAV = "OPEN_NAV";
export const CLOSE_NAV = "CLOSE_NAV";
export const SET_ACTIVE_LINK = "SET_ACTIVE_LINK";
export const GET_COUNTRIES = "GET_COUNTRIES";

export const GET_LEAGUES = "GET_LEAGUES";

export const ADD_NEWS = "ADD_NEWS";
export const GET_NEWS = "GET_NEWS";
export const GET_NEWS_ITEM = "GET_NEWS_ITEM";
export const SET_LIKE = "SET_LIKE";

export const GET_POSITIONS = "GET_POSITIONS";
export const GET_PLAYER = "GET_PLAYER";
export const GET_PLAYERS = "GET_PLAYERS";
export const GET_PLAYER_INFO = "GET_PLAYER_INFO";

export const GET_APPOINT = "GET_APPOINT";
export const GET_CITIES = "GET_CITIES";
export const GET_TOURNAMENTS = "GET_TOURNAMENTS";
export const GET_SUB_TOURNAMENTS = "GET_SUB_TOURNAMENTS";
export const GET_SUB_COMMANDS = "GET_SUB_COMMANDS";
export const GET_COMMANDS_INFO = "GET_COMMANDS_INFO";
export const GET_SUBTOUR_GAMES = "GET_SUBTOUR_GAMES";
export const GET_SUBTOUR_PLAYERS = "GET_SUBTOUR_PLAYERS";

export const GET_CURRENT_GAME = "GET_CURRENT_GAME";
export const GET_CURRENT_GAMES_LIST = "GET_CURRENT_GAMES_LIST";
export const GET_FUTURE_GAMES_LIST = "GET_FUTURE_GAMES_LIST";
export const GET_GAME_PLAYER_LIST = "GET_GAME_PLAYER_LIST";
export const GET_GAME_INFO = "GET_GAME_INFO";
export const GET_EVENT_SETTINGS = "GET_EVENT_SETTINGS";
export const GET_EVENT = "GET_EVENT";
export const GET_PHOTOES = "GET_PHOTOES";
export const GET_VIDEOS = "GET_VIDEOS";

export const GET_COMMANDS = "GET_COMMANDS";
export const GET_COMMAND = "GET_COMMAND";
export const GET_FREE_NUMBERS = "GET_FREE_NUMBERS";
